### ISSUE TITLE
Geohashing site moving

### ISSUE THREAD

**Issue by Dan-Q** [relet/pygeohashing#10]
We're moving the wiki to https://geohashing.site/; the bot will presumably need re-pointing? If you're still happy to run it, please feel free to make the changes yourself - if you're no longer interested in running it, let me know and I'll try to have somebody adopt and adapt it.

**Comment by aperfectring** [comment]
Yes, the bot will need to be pointed to the new geohashing site.

Since I haven't actually gone on any geohashing expeditions in many years at this point, and don't see that changing in the short term, this is probably a good opportunity to see if someone else wants to take over running (and maintaining) the bot.  It's fairly straightforward and trouble free to keep going as it has been, but there's always been room for improvement, and someone more active and engaged could make those improvements.

I'm happy to help anyone in getting it up and going.  I'm also happy to help updating the code for the new site if need be, because even though I haven't been going geohashing, I still think it's a neat thing and would like to ensure it keeps on going.

If there's any trouble in finding someone to run/maintain the bot, I'll keep it going, because it only really requires a computer with python and the pywikipedia module that's constantly running, and I have that. =P

**Comment by aperfectring** [comment]
If you'd like me to spin up the bot to the new site while we look for a new wrangler, please let me know and I'll create the account for it, and let you know so you can give it the bot flag before I let it lose on the new digs.

**Comment by Dan-Q** [comment]
Sure: can you kick it off for now and we'll sort out a "bots needs adopts!" page or the like to try to find new maintainers for them. Thanks for all your help! Just shout here, by email (email is on my Geohashing page), or in IRC to let me know the bot name so I can flag it. Thanks again!

(My python's rusty as hell so I'm probably not the best person to give it the long-term-love it deserves.)

**Comment by relet** [comment]
Does that mean we have some more control over wiki things? We could rewrite the map widget to use for example leaflet?

**Comment by Dan-Q** [comment]
Absolutely!

I've just reimplemented the map widget by copying peeron's (which it was using), fixing the Google API key, removing the non-embedded functionality, and rehosting at map.geohashing.site. But I'd _love_ to see a fresh implementation based on modern needs.

I've also been tweaking a few small personal bugbears, for example you're now allowed to upload tracklogs (.gpx files) directly to the wiki.

**Comment by relet** [comment]
Great news! Thank you so much.
IIRC Google maps has tighter limits for their free service now, so I was just thinking it could unexpectedly drop out when geohashing is taking over the world again. And geohashers are the kind of people who would appreciate being able to edit the map at their geohash locations.

**Comment by Dan-Q** [comment]
Yeah. I've given my credit card to Google if need-be, but if it starts to ramp up then... well, that'll make me work faster to get a better solution out there, won't it?

**Comment by aperfectring** [comment]
The bot user has been created: AperfectBot (same as it ever was).  Please let me know when it has been flagged, and I'll work on getting it pointed to the new wiki, and getting all of the changes pushed up here.

**Comment by Dan-Q** [comment]
Flagged as a bot: go wild!

**Comment by aperfectring** [comment]
Alright, I think I have everything updated to work.  I'm doing a first test with the cron job right now, I ask for help keeping an eye on the dumb ape to make sure it isn't being destructive.  It didn't seem to be when I ran it manually, but I'll be headed to bed before too long, and I'll be busy working during the day tomorrow, so might not be able to stop it if it goes wild.  Use the emergency banana if things go poorly.

**Comment by aperfectring** [comment]
Alright, first round of cron done, and started on the second!  It took about 12 minutes to do a single set, which put it at 5 updates an hour, which means that it'll cycle through about 1 year of "old dates" every day, so full refresh of everything in a bit under 2 weeks.

**Comment by aperfectring** [comment]
Bot is running normally, and has been for a bit now!
